<a href="https://colab.research.google.com/github/ranjithnrjk/PyTorch_basics/blob/main/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Tensors</h1>
It's a multi dimensional array

In [4]:
import torch
import numpy as np

## Lists

In [5]:
my_list = [[1,2,3],[4,5,6]]
my_list

[[1, 2, 3], [4, 5, 6]]

## Numpy Arrays

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.65596872, 0.19600618, 0.16141412, 0.51532533],
       [0.94235628, 0.74180507, 0.2646719 , 0.58072905],
       [0.82123025, 0.7579416 , 0.18912012, 0.75468132]])

In [7]:
np1.dtype

dtype('float64')

## PyTorch Arrays

In [8]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.5011, 0.0063, 0.1758, 0.9106],
        [0.8715, 0.4808, 0.1574, 0.4266],
        [0.5828, 0.1474, 0.5437, 0.7050]])

In [9]:
torch.tensor(np1)

tensor([[0.6560, 0.1960, 0.1614, 0.5153],
        [0.9424, 0.7418, 0.2647, 0.5807],
        [0.8212, 0.7579, 0.1891, 0.7547]], dtype=torch.float64)

In [10]:
torch_1 = torch.arange(10)
torch_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### PyTorch tensor transformations and operations

In [11]:
torch_2 = torch_1.reshape(2, -1)
torch_2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
torch_3 = torch_1.view(2, -1)
torch_3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
torch_1[2] = torch.tensor(10000)
torch_1

tensor([    0,     1, 10000,     3,     4,     5,     6,     7,     8,     9])

In [16]:
torch_2, torch_3

(tensor([[    0,     1, 10000,     3,     4],
         [    5,     6,     7,     8,     9]]),
 tensor([[    0,     1, 10000,     3,     4],
         [    5,     6,     7,     8,     9]]))

In [18]:
torch_2[:, 1:3]

tensor([[    1, 10000],
        [    6,     7]])

### PyTorch tensor Math Operations

In [21]:
tensor_a = torch.tensor([1,2,34,5])
tensor_b = torch.arange(4)

In [26]:
# Addition
tensor_c = torch.add(tensor_a, tensor_b)
print('tensor_c: ', tensor_c)

# Subtract
tensor_d = torch.sub(tensor_a, tensor_b)
print('tensor_d: ',tensor_d)

# Multiply
tensor_e = torch.mul(tensor_a, tensor_b)
print(f'Tensor_e: ', tensor_e)

# Division
tensor_div = tensor_b / tensor_a
print(f'tensor_div: {tensor_div}')

tensor_div_ = torch.div(tensor_b, tensor_a)
print(f"tensor_div_: {tensor_div_}")

# Remianders
tensor_mod = tensor_b % tensor_a
print(f'tensor_mode: {tensor_mod}')

tensor_mod_ = torch.remainder(tensor_b, tensor_a)
print(f'tensor_mod: {tensor_mod_}')

# Exponents
tensor_exp = torch.pow(tensor_a, tensor_b)
print(f"tensor_exp: {tensor_exp}")

tensor_c:  tensor([ 1,  3, 36,  8])
tensor_d:  tensor([ 1,  1, 32,  2])
Tensor_e:  tensor([ 0,  2, 68, 15])
tensor_div: tensor([0.0000, 0.5000, 0.0588, 0.6000])
tensor_div_: tensor([0.0000, 0.5000, 0.0588, 0.6000])
tensor_mode: tensor([0, 1, 2, 3])
tensor_mod: tensor([0, 1, 2, 3])
tensor_exp: tensor([   1,    2, 1156,  125])
